### ISSUE TITLE
Windows 11 - Recursive option on large project fails

### ISSUE THREAD

**Issue by scheurik** [anthonyharrison/sbom4files#5]
When running the "-r" option on a large project folder (with many sub directory levels) on Windows 11, the execution bombs out with the following error below.

In particular, the open source project it was ran against at the top level was: https://github.com/awslabs/visual-asset-management-system 

This was run against a clean Git clone (before NPM installs) 

```
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\sbom4files.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\sbom4files\cli.py", line 170, in main
    if file_scanner.scan_file(entry):
  File "C:\Program Files\Python310\lib\site-packages\sbom4files\filescanner.py", line 157, in scan_file
    mimetype = magic.from_file(str(filename), mime=True)
  File "C:\Program Files\Python310\lib\site-packages\magic\magic.py", line 135, in from_file
    return m.from_file(filename)
  File "C:\Program Files\Python310\lib\site-packages\magic\magic.py", line 91, in from_file
    return self._handle509Bug(e)
  File "C:\Program Files\Python310\lib\site-packages\magic\magic.py", line 100, in _handle509Bug
    raise e
  File "C:\Program Files\Python310\lib\site-packages\magic\magic.py", line 89, in from_file
    return maybe_decode(magic_file(self.cookie, filename))
  File "C:\Program Files\Python310\lib\site-packages\magic\magic.py", line 255, in magic_file
    return _magic_file(cookie, coerce_filename(filename))
  File "C:\Program Files\Python310\lib\site-packages\magic\magic.py", line 196, in errorcheck_null
    raise MagicException(err)
magic.magic.MagicException: b"line I64u: regex error 14 for `^[[:space:]]*class[[:space:]]+[[:digit:][:alpha:]:_]+[[:space:]]*\\{(.*[\n]*)*\\}(;)?$', (failed to get memory)"
```

**Comment by anthonyharrison** [comment]
@scheurik I don't have a Windows 11 system available but I have run the following command on a cloned version of the AWS repository on a Ubuntu based system

`sbom4files -d . -r -p AWS-Asset_system -o /tmp/awslabs1.spdx`

The SBOM is quickly generated and contains 465 file records.

The issue looks like it is related to the Magic library. There are known issues with this library on Windows and I added guidance on how to resolve one of the issues with an import error (details in the README). Have you tried this?

Can you confirm that have tried to run `sbom4files` on a directory without recursing into the subdirectories without any problems?

Can you also confirm that you are running `sbom4files` in a Python virtual machine, using the latest version of `sbom4files`. Can you post the output of the `pip list` command for this environment?

**Comment by anthonyharrison** [comment]
Closed due to no further information being provided.

Tested as follows:

1. Create python virtual environment
2. Install sbom4files into virtual environment
3. Run sbom4files across all of the installed python files `sbom4files -d Lib -p test -r`. Sbom successfully generated (there are over 1800 different files captured).
